# -*- coding: utf-8 -*-
"""Copy of Gradio_Example.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VpJEoAD5OMd-WuYISt3hfGRw_XxSk0UE
"""

from fastai.vision.all import *

import gradio as gr

#|export
def is_cat(x):
  return x[0].isupper()

#|export
learn = load_learner('model.pkl')


#|export
categories = ('Dog','Cat')

#|export
def classify_image(img): 
  pred,idx,probs = learn.predict(img)
  return dict(zip(categories, map(float, probs)))


#|export
image = gr.inputs.Image(shape = (192,192))
label = gr.outputs.Label()
examples = ['dog.jpg','cat.jpg','dunno.jpg']

intf = gr.Interface(fn = classify_image, inputs = image, outputs = label, examples = examples)
intf.launch(inline = False, debug = True)
